server:
  port: 8082
dubbo:
  application:
    name: dubbo-consumer    #服务名称
  registry:
    protocol: zookeeper     #注册中心的协议
    address: 127.0.0.1:2181 #注册中心的地址
  monitor:
    protocol: registry      #连接监控中心